#!/bin/bash

echo "--- begin project specific setup for Skolmat --"

# TODO
# Add project specific setup directives to this file
# It will be called by "container setup-project" (see devcontainer.json postCreateCommand)

add_ha_resource /local/skolmat-card/skolmat-card.js

# link lovelace panel for the skolmat-card (sub module repo)
echo "Linking $WORKSPACE_DIR/skolmat-card/lovelace-panel.yaml to $HA_CONFIG_DIR/panel.yaml"
ln -sf $WORKSPACE_DIR/skolmat-card/lovelace-panel.yaml $HA_CONFIG_DIR/panel.yaml
