title: Skolmat
views:
  - title: Skolmat
    path: skolmat
    cards:

      - type: custom:skolmat-card
        entity: skolmat.skolmaten_se_skutehagen
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.skolmaten_se_skutehagen
        menu_type: week
        header: full

      - type: custom:skolmat-card
        entity: skolmat.foodit_se_backaskolan
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.foodit_se_backaskolan
        menu_type: week
        header: full

      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_kyrkebyskolan
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_kyrkebyskolan
        menu_type: week
        header: full

      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_scheeleskolan
        menu_type: today
        header: full
      - type: custom:skolmat-card
        entity: skolmat.mpi_mashie_com_scheeleskolan
        menu_type: week
        header: full














