- platform: skolmat
  name: "skolmaten.se - Skutehagen"
  unique_id: "foo_bar_skutehag"
  url: "https://skolmaten.se/menu/29f13515-185f-4df5-b39b-bca0a2bc4fc8?school=157fa289-ef68-411d-b2b5-d98014555c02"

- platform: skolmat
  name: "foodit.se - Bäckaskolan"
  url: "https://webmenu.foodit.se/?r=6&m=617&p=883&c=10023&w=0&v=Week"

- platform: skolmat
  name: "menu.matildaplatform.com - Älvkarleby"
  url: "https://menu.matildaplatform.com/meals/week/63fc6e2dccb95f5ce56d8ada_skolor"

- platform: skolmat
  name: mpi.mashie.com - Kyrkebyskolan
  url: "https://mpi.mashie.com/public/app/Arvika%20Kommun/43242677"

- platform: skolmat
  name: mpi.mashie.com - Scheeleskolan
  url: "https://mpi.mashie.com/public/app/K%C3%B6pings%20kommun/d0767b9e"

- platform: skolmat
  name: sodexo.mashie.com - Västra skolan 
  url: "https://sodexo.mashie.com/public/menu/Akademikrogen%20skolor/d47bc6bf"


- platform: skolmat
  name: skolmaten.se - Stadsskogen skola
  url: "https://skolmaten.se/menu/18b53bff-437d-4bb8-a6a4-2380a039557d?school=82c5bb98-79c3-4ba0-a1e2-73b55944c9c5"




  