- platform: skolmat
  name: "skolmaten.se - Skutehagen"
  url: "https://skolmaten.se/skutehagens-skolan"

- platform: skolmat
  name: "foodit.se - Bäckaskolan"
  url: "https://webmenu.foodit.se/?r=6&m=617&p=883&c=10023&w=0&v=Week"

- platform: skolmat
  name: "menu.matildaplatform.com - Älvkarleby"
  url: "https://menu.matildaplatform.com/meals/week/63fc6e2dccb95f5ce56d8ada_skolor"

- platform: skolmat
  name: mpi.mashie.com - Scheeleskolan
  url: "https://mpi.mashie.com/public/app/K%C3%B6pings%20kommun/d0767b9e"

- platform: skolmat
  name: sodexo.mashie.com - Västra skolan
  url: "https://sodexo.mashie.com/public/menu/Akademikrogen%20skolor/d47bc6bf"

- platform: skolmat
  name: mateo.se - Kävlinge utbildning
  url: "https://meny.mateo.se/kavlinge-utbildning/106"

- platform: skolmat
  name: "menu.matildaplatform.com - Dalajärs förskola"
  url: "https://menu.matildaplatform.com/meals/week/6682a34d6337e8ced9340214_dalajars-forskola"
  